version: '2'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
      args:
        - API_ADDRESS=pqapi.uiplay.cn
    volumes: 
      - ${PWD}:/home/nodejs/app
      - /home/nodejs/app/node_modules
    ports:
      - 8080:8080
      - 3000:3000
    command: ws -d dist -s index.html -p 8080 
