export const POST_FETCH_REQUEST = 'POST_FETCH_REQUEST';
export const POST_FETCH_FAILURE = 'POST_FETCH_FAILURE';
export const POST_FETCH_SUCCESS = 'POST_FETCH_SUCCESS';

export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST';
export const POST_UPDATE_FAILURE = 'POST_UPDATE_FAILURE';
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS';

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_FAILURE = 'POST_CREATE_FAILURE';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_FAILURE = 'POST_DELETE_FAILURE';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
